/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as ChecklistIndexRouteImport } from './routes/checklist/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AuthenticationSigninRouteImport } from './routes/authentication/signin'
import { Route as AuthenticationForgotRouteImport } from './routes/authentication/forgot'
import { Route as UserSettingIndexRouteImport } from './routes/user/setting/index'
import { Route as UserInvoicesIndexRouteImport } from './routes/user/invoices/index'
import { Route as UserDashboardIndexRouteImport } from './routes/user/dashboard/index'
import { Route as CrmOpportunitiesIndexRouteImport } from './routes/crm/opportunities/index'
import { Route as CrmLeadsIndexRouteImport } from './routes/crm/leads/index'
import { Route as CrmLeadSourcesIndexRouteImport } from './routes/crm/lead-sources/index'
import { Route as CrmIndustryTypesIndexRouteImport } from './routes/crm/industry-types/index'
import { Route as CrmDashboardIndexRouteImport } from './routes/crm/dashboard/index'
import { Route as CrmContactsIndexRouteImport } from './routes/crm/contacts/index'
import { Route as CrmCalenderIndexRouteImport } from './routes/crm/calender/index'
import { Route as CrmActivitiesIndexRouteImport } from './routes/crm/activities/index'
import { Route as ChecklistTypeIndexRouteImport } from './routes/checklist/type/index'
import { Route as ChecklistRegisterIndexRouteImport } from './routes/checklist/register/index'
import { Route as ChecklistRecordsIndexRouteImport } from './routes/checklist/records/index'
import { Route as ChecklistQuestionIndexRouteImport } from './routes/checklist/question/index'
import { Route as ChecklistMembersIndexRouteImport } from './routes/checklist/members/index'
import { Route as ChecklistMaintenanceIndexRouteImport } from './routes/checklist/maintenance/index'
import { Route as ChecklistMachineIndexRouteImport } from './routes/checklist/machine/index'
import { Route as ChecklistDocTestIndexRouteImport } from './routes/checklist/doc-test/index'
import { Route as ChecklistDashboardIndexRouteImport } from './routes/checklist/dashboard/index'
import { Route as ChecklistChecklistRecordsIndexRouteImport } from './routes/checklist/checklist-records/index'
import { Route as ChecklistCalibrationIndexRouteImport } from './routes/checklist/calibration/index'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminDepartmentsIndexRouteImport } from './routes/admin/departments/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AccountProductsIndexRouteImport } from './routes/account/products/index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrderStatusIndexRouteImport } from './routes/account/order-status/index'
import { Route as AccountInvoicesIndexRouteImport } from './routes/account/invoices/index'
import { Route as AccountInetsIndexRouteImport } from './routes/account/inets/index'
import { Route as AccountDashboardIndexRouteImport } from './routes/account/dashboard/index'
import { Route as AccountCustomersIndexRouteImport } from './routes/account/customers/index'
import { Route as AccountBillingNotesIndexRouteImport } from './routes/account/billing-notes/index'
import { Route as CrmOpportunitiesViewdRouteImport } from './routes/crm/opportunities/viewd'
import { Route as CrmOpportunitiesViewRouteImport } from './routes/crm/opportunities/view'
import { Route as CrmOpportunitiesAddRouteImport } from './routes/crm/opportunities/add'
import { Route as ChecklistTypeEditRouteImport } from './routes/checklist/type/edit'
import { Route as ChecklistTypeAddRouteImport } from './routes/checklist/type/add'
import { Route as ChecklistRegisterViewRouteImport } from './routes/checklist/register/view'
import { Route as ChecklistRegisterAddRouteImport } from './routes/checklist/register/add'
import { Route as ChecklistQuestionEditRouteImport } from './routes/checklist/question/edit'
import { Route as ChecklistQuestionAddRouteImport } from './routes/checklist/question/add'
import { Route as ChecklistMembersViewRouteImport } from './routes/checklist/members/view'
import { Route as ChecklistMembersEditRouteImport } from './routes/checklist/members/edit'
import { Route as ChecklistMembersAddRouteImport } from './routes/checklist/members/add'
import { Route as ChecklistMaintenanceViewRouteImport } from './routes/checklist/maintenance/view'
import { Route as ChecklistMaintenanceEditRouteImport } from './routes/checklist/maintenance/edit'
import { Route as ChecklistMaintenanceAddRouteImport } from './routes/checklist/maintenance/add'
import { Route as ChecklistMachineViewRouteImport } from './routes/checklist/machine/view'
import { Route as ChecklistMachineEditRouteImport } from './routes/checklist/machine/edit'
import { Route as ChecklistMachineAddRouteImport } from './routes/checklist/machine/add'
import { Route as ChecklistKpiViewRouteImport } from './routes/checklist/kpi/view'
import { Route as ChecklistChecklistRecordsViewRouteImport } from './routes/checklist/checklist-records/view'
import { Route as ChecklistChecklistRecordsEditRouteImport } from './routes/checklist/checklist-records/edit'
import { Route as ChecklistChecklistRecordsAddRouteImport } from './routes/checklist/checklist-records/add'
import { Route as ChecklistCalibrationViewRouteImport } from './routes/checklist/calibration/view'
import { Route as ChecklistCalibrationEditRouteImport } from './routes/checklist/calibration/edit'
import { Route as AccountInetsJsonRouteImport } from './routes/account/inets/json'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const ChecklistIndexRoute = ChecklistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChecklistRoute,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AuthenticationSigninRoute = AuthenticationSigninRouteImport.update({
  id: '/authentication/signin',
  path: '/authentication/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationForgotRoute = AuthenticationForgotRouteImport.update({
  id: '/authentication/forgot',
  path: '/authentication/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingIndexRoute = UserSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => UserRoute,
} as any)
const UserInvoicesIndexRoute = UserInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardIndexRoute = UserDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => UserRoute,
} as any)
const CrmOpportunitiesIndexRoute = CrmOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsIndexRoute = CrmLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadSourcesIndexRoute = CrmLeadSourcesIndexRouteImport.update({
  id: '/lead-sources/',
  path: '/lead-sources/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmIndustryTypesIndexRoute = CrmIndustryTypesIndexRouteImport.update({
  id: '/industry-types/',
  path: '/industry-types/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDashboardIndexRoute = CrmDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsIndexRoute = CrmContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCalenderIndexRoute = CrmCalenderIndexRouteImport.update({
  id: '/calender/',
  path: '/calender/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmActivitiesIndexRoute = CrmActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => CrmRoute,
} as any)
const ChecklistTypeIndexRoute = ChecklistTypeIndexRouteImport.update({
  id: '/type/',
  path: '/type/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistRegisterIndexRoute = ChecklistRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistRecordsIndexRoute = ChecklistRecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistQuestionIndexRoute = ChecklistQuestionIndexRouteImport.update({
  id: '/question/',
  path: '/question/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMembersIndexRoute = ChecklistMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMaintenanceIndexRoute =
  ChecklistMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistMachineIndexRoute = ChecklistMachineIndexRouteImport.update({
  id: '/machine/',
  path: '/machine/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistDocTestIndexRoute = ChecklistDocTestIndexRouteImport.update({
  id: '/doc-test/',
  path: '/doc-test/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistDashboardIndexRoute = ChecklistDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistChecklistRecordsIndexRoute =
  ChecklistChecklistRecordsIndexRouteImport.update({
    id: '/checklist-records/',
    path: '/checklist-records/',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistCalibrationIndexRoute =
  ChecklistCalibrationIndexRouteImport.update({
    id: '/calibration/',
    path: '/calibration/',
    getParentRoute: () => ChecklistRoute,
  } as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProductsIndexRoute = AccountProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrderStatusIndexRoute = AccountOrderStatusIndexRouteImport.update({
  id: '/order-status/',
  path: '/order-status/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInvoicesIndexRoute = AccountInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInetsIndexRoute = AccountInetsIndexRouteImport.update({
  id: '/inets/',
  path: '/inets/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDashboardIndexRoute = AccountDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCustomersIndexRoute = AccountCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBillingNotesIndexRoute =
  AccountBillingNotesIndexRouteImport.update({
    id: '/billing-notes/',
    path: '/billing-notes/',
    getParentRoute: () => AccountRoute,
  } as any)
const CrmOpportunitiesViewdRoute = CrmOpportunitiesViewdRouteImport.update({
  id: '/opportunities/viewd',
  path: '/opportunities/viewd',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOpportunitiesViewRoute = CrmOpportunitiesViewRouteImport.update({
  id: '/opportunities/view',
  path: '/opportunities/view',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOpportunitiesAddRoute = CrmOpportunitiesAddRouteImport.update({
  id: '/opportunities/add',
  path: '/opportunities/add',
  getParentRoute: () => CrmRoute,
} as any)
const ChecklistTypeEditRoute = ChecklistTypeEditRouteImport.update({
  id: '/type/edit',
  path: '/type/edit',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistTypeAddRoute = ChecklistTypeAddRouteImport.update({
  id: '/type/add',
  path: '/type/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistRegisterViewRoute = ChecklistRegisterViewRouteImport.update({
  id: '/register/view',
  path: '/register/view',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistRegisterAddRoute = ChecklistRegisterAddRouteImport.update({
  id: '/register/add',
  path: '/register/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistQuestionEditRoute = ChecklistQuestionEditRouteImport.update({
  id: '/question/edit',
  path: '/question/edit',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistQuestionAddRoute = ChecklistQuestionAddRouteImport.update({
  id: '/question/add',
  path: '/question/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMembersViewRoute = ChecklistMembersViewRouteImport.update({
  id: '/members/view',
  path: '/members/view',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMembersEditRoute = ChecklistMembersEditRouteImport.update({
  id: '/members/edit',
  path: '/members/edit',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMembersAddRoute = ChecklistMembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMaintenanceViewRoute =
  ChecklistMaintenanceViewRouteImport.update({
    id: '/maintenance/view',
    path: '/maintenance/view',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistMaintenanceEditRoute =
  ChecklistMaintenanceEditRouteImport.update({
    id: '/maintenance/edit',
    path: '/maintenance/edit',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistMaintenanceAddRoute = ChecklistMaintenanceAddRouteImport.update({
  id: '/maintenance/add',
  path: '/maintenance/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMachineViewRoute = ChecklistMachineViewRouteImport.update({
  id: '/machine/view',
  path: '/machine/view',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMachineEditRoute = ChecklistMachineEditRouteImport.update({
  id: '/machine/edit',
  path: '/machine/edit',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistMachineAddRoute = ChecklistMachineAddRouteImport.update({
  id: '/machine/add',
  path: '/machine/add',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistKpiViewRoute = ChecklistKpiViewRouteImport.update({
  id: '/kpi/view',
  path: '/kpi/view',
  getParentRoute: () => ChecklistRoute,
} as any)
const ChecklistChecklistRecordsViewRoute =
  ChecklistChecklistRecordsViewRouteImport.update({
    id: '/checklist-records/view',
    path: '/checklist-records/view',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistChecklistRecordsEditRoute =
  ChecklistChecklistRecordsEditRouteImport.update({
    id: '/checklist-records/edit',
    path: '/checklist-records/edit',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistChecklistRecordsAddRoute =
  ChecklistChecklistRecordsAddRouteImport.update({
    id: '/checklist-records/add',
    path: '/checklist-records/add',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistCalibrationViewRoute =
  ChecklistCalibrationViewRouteImport.update({
    id: '/calibration/view',
    path: '/calibration/view',
    getParentRoute: () => ChecklistRoute,
  } as any)
const ChecklistCalibrationEditRoute =
  ChecklistCalibrationEditRouteImport.update({
    id: '/calibration/edit',
    path: '/calibration/edit',
    getParentRoute: () => ChecklistRoute,
  } as any)
const AccountInetsJsonRoute = AccountInetsJsonRouteImport.update({
  id: '/inets/json',
  path: '/inets/json',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checklist': typeof ChecklistRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/signin': typeof AuthenticationSigninRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/user/': typeof UserIndexRoute
  '/account/inets/json': typeof AccountInetsJsonRoute
  '/checklist/calibration/edit': typeof ChecklistCalibrationEditRoute
  '/checklist/calibration/view': typeof ChecklistCalibrationViewRoute
  '/checklist/checklist-records/add': typeof ChecklistChecklistRecordsAddRoute
  '/checklist/checklist-records/edit': typeof ChecklistChecklistRecordsEditRoute
  '/checklist/checklist-records/view': typeof ChecklistChecklistRecordsViewRoute
  '/checklist/kpi/view': typeof ChecklistKpiViewRoute
  '/checklist/machine/add': typeof ChecklistMachineAddRoute
  '/checklist/machine/edit': typeof ChecklistMachineEditRoute
  '/checklist/machine/view': typeof ChecklistMachineViewRoute
  '/checklist/maintenance/add': typeof ChecklistMaintenanceAddRoute
  '/checklist/maintenance/edit': typeof ChecklistMaintenanceEditRoute
  '/checklist/maintenance/view': typeof ChecklistMaintenanceViewRoute
  '/checklist/members/add': typeof ChecklistMembersAddRoute
  '/checklist/members/edit': typeof ChecklistMembersEditRoute
  '/checklist/members/view': typeof ChecklistMembersViewRoute
  '/checklist/question/add': typeof ChecklistQuestionAddRoute
  '/checklist/question/edit': typeof ChecklistQuestionEditRoute
  '/checklist/register/add': typeof ChecklistRegisterAddRoute
  '/checklist/register/view': typeof ChecklistRegisterViewRoute
  '/checklist/type/add': typeof ChecklistTypeAddRoute
  '/checklist/type/edit': typeof ChecklistTypeEditRoute
  '/crm/opportunities/add': typeof CrmOpportunitiesAddRoute
  '/crm/opportunities/view': typeof CrmOpportunitiesViewRoute
  '/crm/opportunities/viewd': typeof CrmOpportunitiesViewdRoute
  '/account/billing-notes': typeof AccountBillingNotesIndexRoute
  '/account/customers': typeof AccountCustomersIndexRoute
  '/account/dashboard': typeof AccountDashboardIndexRoute
  '/account/inets': typeof AccountInetsIndexRoute
  '/account/invoices': typeof AccountInvoicesIndexRoute
  '/account/order-status': typeof AccountOrderStatusIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/products': typeof AccountProductsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/checklist/calibration': typeof ChecklistCalibrationIndexRoute
  '/checklist/checklist-records': typeof ChecklistChecklistRecordsIndexRoute
  '/checklist/dashboard': typeof ChecklistDashboardIndexRoute
  '/checklist/doc-test': typeof ChecklistDocTestIndexRoute
  '/checklist/machine': typeof ChecklistMachineIndexRoute
  '/checklist/maintenance': typeof ChecklistMaintenanceIndexRoute
  '/checklist/members': typeof ChecklistMembersIndexRoute
  '/checklist/question': typeof ChecklistQuestionIndexRoute
  '/checklist/records': typeof ChecklistRecordsIndexRoute
  '/checklist/register': typeof ChecklistRegisterIndexRoute
  '/checklist/type': typeof ChecklistTypeIndexRoute
  '/crm/activities': typeof CrmActivitiesIndexRoute
  '/crm/calender': typeof CrmCalenderIndexRoute
  '/crm/contacts': typeof CrmContactsIndexRoute
  '/crm/dashboard': typeof CrmDashboardIndexRoute
  '/crm/industry-types': typeof CrmIndustryTypesIndexRoute
  '/crm/lead-sources': typeof CrmLeadSourcesIndexRoute
  '/crm/leads': typeof CrmLeadsIndexRoute
  '/crm/opportunities': typeof CrmOpportunitiesIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/user/invoices': typeof UserInvoicesIndexRoute
  '/user/setting': typeof UserSettingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/signin': typeof AuthenticationSigninRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/checklist': typeof ChecklistIndexRoute
  '/crm': typeof CrmIndexRoute
  '/user': typeof UserIndexRoute
  '/account/inets/json': typeof AccountInetsJsonRoute
  '/checklist/calibration/edit': typeof ChecklistCalibrationEditRoute
  '/checklist/calibration/view': typeof ChecklistCalibrationViewRoute
  '/checklist/checklist-records/add': typeof ChecklistChecklistRecordsAddRoute
  '/checklist/checklist-records/edit': typeof ChecklistChecklistRecordsEditRoute
  '/checklist/checklist-records/view': typeof ChecklistChecklistRecordsViewRoute
  '/checklist/kpi/view': typeof ChecklistKpiViewRoute
  '/checklist/machine/add': typeof ChecklistMachineAddRoute
  '/checklist/machine/edit': typeof ChecklistMachineEditRoute
  '/checklist/machine/view': typeof ChecklistMachineViewRoute
  '/checklist/maintenance/add': typeof ChecklistMaintenanceAddRoute
  '/checklist/maintenance/edit': typeof ChecklistMaintenanceEditRoute
  '/checklist/maintenance/view': typeof ChecklistMaintenanceViewRoute
  '/checklist/members/add': typeof ChecklistMembersAddRoute
  '/checklist/members/edit': typeof ChecklistMembersEditRoute
  '/checklist/members/view': typeof ChecklistMembersViewRoute
  '/checklist/question/add': typeof ChecklistQuestionAddRoute
  '/checklist/question/edit': typeof ChecklistQuestionEditRoute
  '/checklist/register/add': typeof ChecklistRegisterAddRoute
  '/checklist/register/view': typeof ChecklistRegisterViewRoute
  '/checklist/type/add': typeof ChecklistTypeAddRoute
  '/checklist/type/edit': typeof ChecklistTypeEditRoute
  '/crm/opportunities/add': typeof CrmOpportunitiesAddRoute
  '/crm/opportunities/view': typeof CrmOpportunitiesViewRoute
  '/crm/opportunities/viewd': typeof CrmOpportunitiesViewdRoute
  '/account/billing-notes': typeof AccountBillingNotesIndexRoute
  '/account/customers': typeof AccountCustomersIndexRoute
  '/account/dashboard': typeof AccountDashboardIndexRoute
  '/account/inets': typeof AccountInetsIndexRoute
  '/account/invoices': typeof AccountInvoicesIndexRoute
  '/account/order-status': typeof AccountOrderStatusIndexRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/products': typeof AccountProductsIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/checklist/calibration': typeof ChecklistCalibrationIndexRoute
  '/checklist/checklist-records': typeof ChecklistChecklistRecordsIndexRoute
  '/checklist/dashboard': typeof ChecklistDashboardIndexRoute
  '/checklist/doc-test': typeof ChecklistDocTestIndexRoute
  '/checklist/machine': typeof ChecklistMachineIndexRoute
  '/checklist/maintenance': typeof ChecklistMaintenanceIndexRoute
  '/checklist/members': typeof ChecklistMembersIndexRoute
  '/checklist/question': typeof ChecklistQuestionIndexRoute
  '/checklist/records': typeof ChecklistRecordsIndexRoute
  '/checklist/register': typeof ChecklistRegisterIndexRoute
  '/checklist/type': typeof ChecklistTypeIndexRoute
  '/crm/activities': typeof CrmActivitiesIndexRoute
  '/crm/calender': typeof CrmCalenderIndexRoute
  '/crm/contacts': typeof CrmContactsIndexRoute
  '/crm/dashboard': typeof CrmDashboardIndexRoute
  '/crm/industry-types': typeof CrmIndustryTypesIndexRoute
  '/crm/lead-sources': typeof CrmLeadSourcesIndexRoute
  '/crm/leads': typeof CrmLeadsIndexRoute
  '/crm/opportunities': typeof CrmOpportunitiesIndexRoute
  '/user/dashboard': typeof UserDashboardIndexRoute
  '/user/invoices': typeof UserInvoicesIndexRoute
  '/user/setting': typeof UserSettingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checklist': typeof ChecklistRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/authentication/forgot': typeof AuthenticationForgotRoute
  '/authentication/signin': typeof AuthenticationSigninRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/user/': typeof UserIndexRoute
  '/account/inets/json': typeof AccountInetsJsonRoute
  '/checklist/calibration/edit': typeof ChecklistCalibrationEditRoute
  '/checklist/calibration/view': typeof ChecklistCalibrationViewRoute
  '/checklist/checklist-records/add': typeof ChecklistChecklistRecordsAddRoute
  '/checklist/checklist-records/edit': typeof ChecklistChecklistRecordsEditRoute
  '/checklist/checklist-records/view': typeof ChecklistChecklistRecordsViewRoute
  '/checklist/kpi/view': typeof ChecklistKpiViewRoute
  '/checklist/machine/add': typeof ChecklistMachineAddRoute
  '/checklist/machine/edit': typeof ChecklistMachineEditRoute
  '/checklist/machine/view': typeof ChecklistMachineViewRoute
  '/checklist/maintenance/add': typeof ChecklistMaintenanceAddRoute
  '/checklist/maintenance/edit': typeof ChecklistMaintenanceEditRoute
  '/checklist/maintenance/view': typeof ChecklistMaintenanceViewRoute
  '/checklist/members/add': typeof ChecklistMembersAddRoute
  '/checklist/members/edit': typeof ChecklistMembersEditRoute
  '/checklist/members/view': typeof ChecklistMembersViewRoute
  '/checklist/question/add': typeof ChecklistQuestionAddRoute
  '/checklist/question/edit': typeof ChecklistQuestionEditRoute
  '/checklist/register/add': typeof ChecklistRegisterAddRoute
  '/checklist/register/view': typeof ChecklistRegisterViewRoute
  '/checklist/type/add': typeof ChecklistTypeAddRoute
  '/checklist/type/edit': typeof ChecklistTypeEditRoute
  '/crm/opportunities/add': typeof CrmOpportunitiesAddRoute
  '/crm/opportunities/view': typeof CrmOpportunitiesViewRoute
  '/crm/opportunities/viewd': typeof CrmOpportunitiesViewdRoute
  '/account/billing-notes/': typeof AccountBillingNotesIndexRoute
  '/account/customers/': typeof AccountCustomersIndexRoute
  '/account/dashboard/': typeof AccountDashboardIndexRoute
  '/account/inets/': typeof AccountInetsIndexRoute
  '/account/invoices/': typeof AccountInvoicesIndexRoute
  '/account/order-status/': typeof AccountOrderStatusIndexRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/products/': typeof AccountProductsIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/checklist/calibration/': typeof ChecklistCalibrationIndexRoute
  '/checklist/checklist-records/': typeof ChecklistChecklistRecordsIndexRoute
  '/checklist/dashboard/': typeof ChecklistDashboardIndexRoute
  '/checklist/doc-test/': typeof ChecklistDocTestIndexRoute
  '/checklist/machine/': typeof ChecklistMachineIndexRoute
  '/checklist/maintenance/': typeof ChecklistMaintenanceIndexRoute
  '/checklist/members/': typeof ChecklistMembersIndexRoute
  '/checklist/question/': typeof ChecklistQuestionIndexRoute
  '/checklist/records/': typeof ChecklistRecordsIndexRoute
  '/checklist/register/': typeof ChecklistRegisterIndexRoute
  '/checklist/type/': typeof ChecklistTypeIndexRoute
  '/crm/activities/': typeof CrmActivitiesIndexRoute
  '/crm/calender/': typeof CrmCalenderIndexRoute
  '/crm/contacts/': typeof CrmContactsIndexRoute
  '/crm/dashboard/': typeof CrmDashboardIndexRoute
  '/crm/industry-types/': typeof CrmIndustryTypesIndexRoute
  '/crm/lead-sources/': typeof CrmLeadSourcesIndexRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
  '/crm/opportunities/': typeof CrmOpportunitiesIndexRoute
  '/user/dashboard/': typeof UserDashboardIndexRoute
  '/user/invoices/': typeof UserInvoicesIndexRoute
  '/user/setting/': typeof UserSettingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checklist'
    | '/crm'
    | '/user'
    | '/authentication/forgot'
    | '/authentication/signin'
    | '/account/'
    | '/admin/'
    | '/authentication'
    | '/checklist/'
    | '/crm/'
    | '/user/'
    | '/account/inets/json'
    | '/checklist/calibration/edit'
    | '/checklist/calibration/view'
    | '/checklist/checklist-records/add'
    | '/checklist/checklist-records/edit'
    | '/checklist/checklist-records/view'
    | '/checklist/kpi/view'
    | '/checklist/machine/add'
    | '/checklist/machine/edit'
    | '/checklist/machine/view'
    | '/checklist/maintenance/add'
    | '/checklist/maintenance/edit'
    | '/checklist/maintenance/view'
    | '/checklist/members/add'
    | '/checklist/members/edit'
    | '/checklist/members/view'
    | '/checklist/question/add'
    | '/checklist/question/edit'
    | '/checklist/register/add'
    | '/checklist/register/view'
    | '/checklist/type/add'
    | '/checklist/type/edit'
    | '/crm/opportunities/add'
    | '/crm/opportunities/view'
    | '/crm/opportunities/viewd'
    | '/account/billing-notes'
    | '/account/customers'
    | '/account/dashboard'
    | '/account/inets'
    | '/account/invoices'
    | '/account/order-status'
    | '/account/orders'
    | '/account/products'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/roles'
    | '/admin/sessions'
    | '/checklist/calibration'
    | '/checklist/checklist-records'
    | '/checklist/dashboard'
    | '/checklist/doc-test'
    | '/checklist/machine'
    | '/checklist/maintenance'
    | '/checklist/members'
    | '/checklist/question'
    | '/checklist/records'
    | '/checklist/register'
    | '/checklist/type'
    | '/crm/activities'
    | '/crm/calender'
    | '/crm/contacts'
    | '/crm/dashboard'
    | '/crm/industry-types'
    | '/crm/lead-sources'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/user/dashboard'
    | '/user/invoices'
    | '/user/setting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/forgot'
    | '/authentication/signin'
    | '/account'
    | '/admin'
    | '/authentication'
    | '/checklist'
    | '/crm'
    | '/user'
    | '/account/inets/json'
    | '/checklist/calibration/edit'
    | '/checklist/calibration/view'
    | '/checklist/checklist-records/add'
    | '/checklist/checklist-records/edit'
    | '/checklist/checklist-records/view'
    | '/checklist/kpi/view'
    | '/checklist/machine/add'
    | '/checklist/machine/edit'
    | '/checklist/machine/view'
    | '/checklist/maintenance/add'
    | '/checklist/maintenance/edit'
    | '/checklist/maintenance/view'
    | '/checklist/members/add'
    | '/checklist/members/edit'
    | '/checklist/members/view'
    | '/checklist/question/add'
    | '/checklist/question/edit'
    | '/checklist/register/add'
    | '/checklist/register/view'
    | '/checklist/type/add'
    | '/checklist/type/edit'
    | '/crm/opportunities/add'
    | '/crm/opportunities/view'
    | '/crm/opportunities/viewd'
    | '/account/billing-notes'
    | '/account/customers'
    | '/account/dashboard'
    | '/account/inets'
    | '/account/invoices'
    | '/account/order-status'
    | '/account/orders'
    | '/account/products'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/roles'
    | '/admin/sessions'
    | '/checklist/calibration'
    | '/checklist/checklist-records'
    | '/checklist/dashboard'
    | '/checklist/doc-test'
    | '/checklist/machine'
    | '/checklist/maintenance'
    | '/checklist/members'
    | '/checklist/question'
    | '/checklist/records'
    | '/checklist/register'
    | '/checklist/type'
    | '/crm/activities'
    | '/crm/calender'
    | '/crm/contacts'
    | '/crm/dashboard'
    | '/crm/industry-types'
    | '/crm/lead-sources'
    | '/crm/leads'
    | '/crm/opportunities'
    | '/user/dashboard'
    | '/user/invoices'
    | '/user/setting'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checklist'
    | '/crm'
    | '/user'
    | '/authentication/forgot'
    | '/authentication/signin'
    | '/account/'
    | '/admin/'
    | '/authentication/'
    | '/checklist/'
    | '/crm/'
    | '/user/'
    | '/account/inets/json'
    | '/checklist/calibration/edit'
    | '/checklist/calibration/view'
    | '/checklist/checklist-records/add'
    | '/checklist/checklist-records/edit'
    | '/checklist/checklist-records/view'
    | '/checklist/kpi/view'
    | '/checklist/machine/add'
    | '/checklist/machine/edit'
    | '/checklist/machine/view'
    | '/checklist/maintenance/add'
    | '/checklist/maintenance/edit'
    | '/checklist/maintenance/view'
    | '/checklist/members/add'
    | '/checklist/members/edit'
    | '/checklist/members/view'
    | '/checklist/question/add'
    | '/checklist/question/edit'
    | '/checklist/register/add'
    | '/checklist/register/view'
    | '/checklist/type/add'
    | '/checklist/type/edit'
    | '/crm/opportunities/add'
    | '/crm/opportunities/view'
    | '/crm/opportunities/viewd'
    | '/account/billing-notes/'
    | '/account/customers/'
    | '/account/dashboard/'
    | '/account/inets/'
    | '/account/invoices/'
    | '/account/order-status/'
    | '/account/orders/'
    | '/account/products/'
    | '/admin/dashboard/'
    | '/admin/departments/'
    | '/admin/roles/'
    | '/admin/sessions/'
    | '/checklist/calibration/'
    | '/checklist/checklist-records/'
    | '/checklist/dashboard/'
    | '/checklist/doc-test/'
    | '/checklist/machine/'
    | '/checklist/maintenance/'
    | '/checklist/members/'
    | '/checklist/question/'
    | '/checklist/records/'
    | '/checklist/register/'
    | '/checklist/type/'
    | '/crm/activities/'
    | '/crm/calender/'
    | '/crm/contacts/'
    | '/crm/dashboard/'
    | '/crm/industry-types/'
    | '/crm/lead-sources/'
    | '/crm/leads/'
    | '/crm/opportunities/'
    | '/user/dashboard/'
    | '/user/invoices/'
    | '/user/setting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ChecklistRoute: typeof ChecklistRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AuthenticationForgotRoute: typeof AuthenticationForgotRoute
  AuthenticationSigninRoute: typeof AuthenticationSigninRoute
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/checklist/': {
      id: '/checklist/'
      path: '/'
      fullPath: '/checklist/'
      preLoaderRoute: typeof ChecklistIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/authentication/signin': {
      id: '/authentication/signin'
      path: '/authentication/signin'
      fullPath: '/authentication/signin'
      preLoaderRoute: typeof AuthenticationSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/forgot': {
      id: '/authentication/forgot'
      path: '/authentication/forgot'
      fullPath: '/authentication/forgot'
      preLoaderRoute: typeof AuthenticationForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/setting/': {
      id: '/user/setting/'
      path: '/setting'
      fullPath: '/user/setting'
      preLoaderRoute: typeof UserSettingIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/invoices/': {
      id: '/user/invoices/'
      path: '/invoices'
      fullPath: '/user/invoices'
      preLoaderRoute: typeof UserInvoicesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard/': {
      id: '/user/dashboard/'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/crm/opportunities/': {
      id: '/crm/opportunities/'
      path: '/opportunities'
      fullPath: '/crm/opportunities'
      preLoaderRoute: typeof CrmOpportunitiesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads/': {
      id: '/crm/leads/'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/lead-sources/': {
      id: '/crm/lead-sources/'
      path: '/lead-sources'
      fullPath: '/crm/lead-sources'
      preLoaderRoute: typeof CrmLeadSourcesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/industry-types/': {
      id: '/crm/industry-types/'
      path: '/industry-types'
      fullPath: '/crm/industry-types'
      preLoaderRoute: typeof CrmIndustryTypesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/dashboard/': {
      id: '/crm/dashboard/'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof CrmDashboardIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts/': {
      id: '/crm/contacts/'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/calender/': {
      id: '/crm/calender/'
      path: '/calender'
      fullPath: '/crm/calender'
      preLoaderRoute: typeof CrmCalenderIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/activities/': {
      id: '/crm/activities/'
      path: '/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof CrmActivitiesIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/checklist/type/': {
      id: '/checklist/type/'
      path: '/type'
      fullPath: '/checklist/type'
      preLoaderRoute: typeof ChecklistTypeIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/register/': {
      id: '/checklist/register/'
      path: '/register'
      fullPath: '/checklist/register'
      preLoaderRoute: typeof ChecklistRegisterIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/records/': {
      id: '/checklist/records/'
      path: '/records'
      fullPath: '/checklist/records'
      preLoaderRoute: typeof ChecklistRecordsIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/question/': {
      id: '/checklist/question/'
      path: '/question'
      fullPath: '/checklist/question'
      preLoaderRoute: typeof ChecklistQuestionIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/members/': {
      id: '/checklist/members/'
      path: '/members'
      fullPath: '/checklist/members'
      preLoaderRoute: typeof ChecklistMembersIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/maintenance/': {
      id: '/checklist/maintenance/'
      path: '/maintenance'
      fullPath: '/checklist/maintenance'
      preLoaderRoute: typeof ChecklistMaintenanceIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/machine/': {
      id: '/checklist/machine/'
      path: '/machine'
      fullPath: '/checklist/machine'
      preLoaderRoute: typeof ChecklistMachineIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/doc-test/': {
      id: '/checklist/doc-test/'
      path: '/doc-test'
      fullPath: '/checklist/doc-test'
      preLoaderRoute: typeof ChecklistDocTestIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/dashboard/': {
      id: '/checklist/dashboard/'
      path: '/dashboard'
      fullPath: '/checklist/dashboard'
      preLoaderRoute: typeof ChecklistDashboardIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/checklist-records/': {
      id: '/checklist/checklist-records/'
      path: '/checklist-records'
      fullPath: '/checklist/checklist-records'
      preLoaderRoute: typeof ChecklistChecklistRecordsIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/calibration/': {
      id: '/checklist/calibration/'
      path: '/calibration'
      fullPath: '/checklist/calibration'
      preLoaderRoute: typeof ChecklistCalibrationIndexRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/products/': {
      id: '/account/products/'
      path: '/products'
      fullPath: '/account/products'
      preLoaderRoute: typeof AccountProductsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/order-status/': {
      id: '/account/order-status/'
      path: '/order-status'
      fullPath: '/account/order-status'
      preLoaderRoute: typeof AccountOrderStatusIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/invoices/': {
      id: '/account/invoices/'
      path: '/invoices'
      fullPath: '/account/invoices'
      preLoaderRoute: typeof AccountInvoicesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/inets/': {
      id: '/account/inets/'
      path: '/inets'
      fullPath: '/account/inets'
      preLoaderRoute: typeof AccountInetsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/dashboard/': {
      id: '/account/dashboard/'
      path: '/dashboard'
      fullPath: '/account/dashboard'
      preLoaderRoute: typeof AccountDashboardIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/customers/': {
      id: '/account/customers/'
      path: '/customers'
      fullPath: '/account/customers'
      preLoaderRoute: typeof AccountCustomersIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/billing-notes/': {
      id: '/account/billing-notes/'
      path: '/billing-notes'
      fullPath: '/account/billing-notes'
      preLoaderRoute: typeof AccountBillingNotesIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/crm/opportunities/viewd': {
      id: '/crm/opportunities/viewd'
      path: '/opportunities/viewd'
      fullPath: '/crm/opportunities/viewd'
      preLoaderRoute: typeof CrmOpportunitiesViewdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/opportunities/view': {
      id: '/crm/opportunities/view'
      path: '/opportunities/view'
      fullPath: '/crm/opportunities/view'
      preLoaderRoute: typeof CrmOpportunitiesViewRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/opportunities/add': {
      id: '/crm/opportunities/add'
      path: '/opportunities/add'
      fullPath: '/crm/opportunities/add'
      preLoaderRoute: typeof CrmOpportunitiesAddRouteImport
      parentRoute: typeof CrmRoute
    }
    '/checklist/type/edit': {
      id: '/checklist/type/edit'
      path: '/type/edit'
      fullPath: '/checklist/type/edit'
      preLoaderRoute: typeof ChecklistTypeEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/type/add': {
      id: '/checklist/type/add'
      path: '/type/add'
      fullPath: '/checklist/type/add'
      preLoaderRoute: typeof ChecklistTypeAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/register/view': {
      id: '/checklist/register/view'
      path: '/register/view'
      fullPath: '/checklist/register/view'
      preLoaderRoute: typeof ChecklistRegisterViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/register/add': {
      id: '/checklist/register/add'
      path: '/register/add'
      fullPath: '/checklist/register/add'
      preLoaderRoute: typeof ChecklistRegisterAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/question/edit': {
      id: '/checklist/question/edit'
      path: '/question/edit'
      fullPath: '/checklist/question/edit'
      preLoaderRoute: typeof ChecklistQuestionEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/question/add': {
      id: '/checklist/question/add'
      path: '/question/add'
      fullPath: '/checklist/question/add'
      preLoaderRoute: typeof ChecklistQuestionAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/members/view': {
      id: '/checklist/members/view'
      path: '/members/view'
      fullPath: '/checklist/members/view'
      preLoaderRoute: typeof ChecklistMembersViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/members/edit': {
      id: '/checklist/members/edit'
      path: '/members/edit'
      fullPath: '/checklist/members/edit'
      preLoaderRoute: typeof ChecklistMembersEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/members/add': {
      id: '/checklist/members/add'
      path: '/members/add'
      fullPath: '/checklist/members/add'
      preLoaderRoute: typeof ChecklistMembersAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/maintenance/view': {
      id: '/checklist/maintenance/view'
      path: '/maintenance/view'
      fullPath: '/checklist/maintenance/view'
      preLoaderRoute: typeof ChecklistMaintenanceViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/maintenance/edit': {
      id: '/checklist/maintenance/edit'
      path: '/maintenance/edit'
      fullPath: '/checklist/maintenance/edit'
      preLoaderRoute: typeof ChecklistMaintenanceEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/maintenance/add': {
      id: '/checklist/maintenance/add'
      path: '/maintenance/add'
      fullPath: '/checklist/maintenance/add'
      preLoaderRoute: typeof ChecklistMaintenanceAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/machine/view': {
      id: '/checklist/machine/view'
      path: '/machine/view'
      fullPath: '/checklist/machine/view'
      preLoaderRoute: typeof ChecklistMachineViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/machine/edit': {
      id: '/checklist/machine/edit'
      path: '/machine/edit'
      fullPath: '/checklist/machine/edit'
      preLoaderRoute: typeof ChecklistMachineEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/machine/add': {
      id: '/checklist/machine/add'
      path: '/machine/add'
      fullPath: '/checklist/machine/add'
      preLoaderRoute: typeof ChecklistMachineAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/kpi/view': {
      id: '/checklist/kpi/view'
      path: '/kpi/view'
      fullPath: '/checklist/kpi/view'
      preLoaderRoute: typeof ChecklistKpiViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/checklist-records/view': {
      id: '/checklist/checklist-records/view'
      path: '/checklist-records/view'
      fullPath: '/checklist/checklist-records/view'
      preLoaderRoute: typeof ChecklistChecklistRecordsViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/checklist-records/edit': {
      id: '/checklist/checklist-records/edit'
      path: '/checklist-records/edit'
      fullPath: '/checklist/checklist-records/edit'
      preLoaderRoute: typeof ChecklistChecklistRecordsEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/checklist-records/add': {
      id: '/checklist/checklist-records/add'
      path: '/checklist-records/add'
      fullPath: '/checklist/checklist-records/add'
      preLoaderRoute: typeof ChecklistChecklistRecordsAddRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/calibration/view': {
      id: '/checklist/calibration/view'
      path: '/calibration/view'
      fullPath: '/checklist/calibration/view'
      preLoaderRoute: typeof ChecklistCalibrationViewRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/checklist/calibration/edit': {
      id: '/checklist/calibration/edit'
      path: '/calibration/edit'
      fullPath: '/checklist/calibration/edit'
      preLoaderRoute: typeof ChecklistCalibrationEditRouteImport
      parentRoute: typeof ChecklistRoute
    }
    '/account/inets/json': {
      id: '/account/inets/json'
      path: '/inets/json'
      fullPath: '/account/inets/json'
      preLoaderRoute: typeof AccountInetsJsonRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountInetsJsonRoute: typeof AccountInetsJsonRoute
  AccountBillingNotesIndexRoute: typeof AccountBillingNotesIndexRoute
  AccountCustomersIndexRoute: typeof AccountCustomersIndexRoute
  AccountDashboardIndexRoute: typeof AccountDashboardIndexRoute
  AccountInetsIndexRoute: typeof AccountInetsIndexRoute
  AccountInvoicesIndexRoute: typeof AccountInvoicesIndexRoute
  AccountOrderStatusIndexRoute: typeof AccountOrderStatusIndexRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
  AccountProductsIndexRoute: typeof AccountProductsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountInetsJsonRoute: AccountInetsJsonRoute,
  AccountBillingNotesIndexRoute: AccountBillingNotesIndexRoute,
  AccountCustomersIndexRoute: AccountCustomersIndexRoute,
  AccountDashboardIndexRoute: AccountDashboardIndexRoute,
  AccountInetsIndexRoute: AccountInetsIndexRoute,
  AccountInvoicesIndexRoute: AccountInvoicesIndexRoute,
  AccountOrderStatusIndexRoute: AccountOrderStatusIndexRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
  AccountProductsIndexRoute: AccountProductsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ChecklistRouteChildren {
  ChecklistIndexRoute: typeof ChecklistIndexRoute
  ChecklistCalibrationEditRoute: typeof ChecklistCalibrationEditRoute
  ChecklistCalibrationViewRoute: typeof ChecklistCalibrationViewRoute
  ChecklistChecklistRecordsAddRoute: typeof ChecklistChecklistRecordsAddRoute
  ChecklistChecklistRecordsEditRoute: typeof ChecklistChecklistRecordsEditRoute
  ChecklistChecklistRecordsViewRoute: typeof ChecklistChecklistRecordsViewRoute
  ChecklistKpiViewRoute: typeof ChecklistKpiViewRoute
  ChecklistMachineAddRoute: typeof ChecklistMachineAddRoute
  ChecklistMachineEditRoute: typeof ChecklistMachineEditRoute
  ChecklistMachineViewRoute: typeof ChecklistMachineViewRoute
  ChecklistMaintenanceAddRoute: typeof ChecklistMaintenanceAddRoute
  ChecklistMaintenanceEditRoute: typeof ChecklistMaintenanceEditRoute
  ChecklistMaintenanceViewRoute: typeof ChecklistMaintenanceViewRoute
  ChecklistMembersAddRoute: typeof ChecklistMembersAddRoute
  ChecklistMembersEditRoute: typeof ChecklistMembersEditRoute
  ChecklistMembersViewRoute: typeof ChecklistMembersViewRoute
  ChecklistQuestionAddRoute: typeof ChecklistQuestionAddRoute
  ChecklistQuestionEditRoute: typeof ChecklistQuestionEditRoute
  ChecklistRegisterAddRoute: typeof ChecklistRegisterAddRoute
  ChecklistRegisterViewRoute: typeof ChecklistRegisterViewRoute
  ChecklistTypeAddRoute: typeof ChecklistTypeAddRoute
  ChecklistTypeEditRoute: typeof ChecklistTypeEditRoute
  ChecklistCalibrationIndexRoute: typeof ChecklistCalibrationIndexRoute
  ChecklistChecklistRecordsIndexRoute: typeof ChecklistChecklistRecordsIndexRoute
  ChecklistDashboardIndexRoute: typeof ChecklistDashboardIndexRoute
  ChecklistDocTestIndexRoute: typeof ChecklistDocTestIndexRoute
  ChecklistMachineIndexRoute: typeof ChecklistMachineIndexRoute
  ChecklistMaintenanceIndexRoute: typeof ChecklistMaintenanceIndexRoute
  ChecklistMembersIndexRoute: typeof ChecklistMembersIndexRoute
  ChecklistQuestionIndexRoute: typeof ChecklistQuestionIndexRoute
  ChecklistRecordsIndexRoute: typeof ChecklistRecordsIndexRoute
  ChecklistRegisterIndexRoute: typeof ChecklistRegisterIndexRoute
  ChecklistTypeIndexRoute: typeof ChecklistTypeIndexRoute
}

const ChecklistRouteChildren: ChecklistRouteChildren = {
  ChecklistIndexRoute: ChecklistIndexRoute,
  ChecklistCalibrationEditRoute: ChecklistCalibrationEditRoute,
  ChecklistCalibrationViewRoute: ChecklistCalibrationViewRoute,
  ChecklistChecklistRecordsAddRoute: ChecklistChecklistRecordsAddRoute,
  ChecklistChecklistRecordsEditRoute: ChecklistChecklistRecordsEditRoute,
  ChecklistChecklistRecordsViewRoute: ChecklistChecklistRecordsViewRoute,
  ChecklistKpiViewRoute: ChecklistKpiViewRoute,
  ChecklistMachineAddRoute: ChecklistMachineAddRoute,
  ChecklistMachineEditRoute: ChecklistMachineEditRoute,
  ChecklistMachineViewRoute: ChecklistMachineViewRoute,
  ChecklistMaintenanceAddRoute: ChecklistMaintenanceAddRoute,
  ChecklistMaintenanceEditRoute: ChecklistMaintenanceEditRoute,
  ChecklistMaintenanceViewRoute: ChecklistMaintenanceViewRoute,
  ChecklistMembersAddRoute: ChecklistMembersAddRoute,
  ChecklistMembersEditRoute: ChecklistMembersEditRoute,
  ChecklistMembersViewRoute: ChecklistMembersViewRoute,
  ChecklistQuestionAddRoute: ChecklistQuestionAddRoute,
  ChecklistQuestionEditRoute: ChecklistQuestionEditRoute,
  ChecklistRegisterAddRoute: ChecklistRegisterAddRoute,
  ChecklistRegisterViewRoute: ChecklistRegisterViewRoute,
  ChecklistTypeAddRoute: ChecklistTypeAddRoute,
  ChecklistTypeEditRoute: ChecklistTypeEditRoute,
  ChecklistCalibrationIndexRoute: ChecklistCalibrationIndexRoute,
  ChecklistChecklistRecordsIndexRoute: ChecklistChecklistRecordsIndexRoute,
  ChecklistDashboardIndexRoute: ChecklistDashboardIndexRoute,
  ChecklistDocTestIndexRoute: ChecklistDocTestIndexRoute,
  ChecklistMachineIndexRoute: ChecklistMachineIndexRoute,
  ChecklistMaintenanceIndexRoute: ChecklistMaintenanceIndexRoute,
  ChecklistMembersIndexRoute: ChecklistMembersIndexRoute,
  ChecklistQuestionIndexRoute: ChecklistQuestionIndexRoute,
  ChecklistRecordsIndexRoute: ChecklistRecordsIndexRoute,
  ChecklistRegisterIndexRoute: ChecklistRegisterIndexRoute,
  ChecklistTypeIndexRoute: ChecklistTypeIndexRoute,
}

const ChecklistRouteWithChildren = ChecklistRoute._addFileChildren(
  ChecklistRouteChildren,
)

interface CrmRouteChildren {
  CrmIndexRoute: typeof CrmIndexRoute
  CrmOpportunitiesAddRoute: typeof CrmOpportunitiesAddRoute
  CrmOpportunitiesViewRoute: typeof CrmOpportunitiesViewRoute
  CrmOpportunitiesViewdRoute: typeof CrmOpportunitiesViewdRoute
  CrmActivitiesIndexRoute: typeof CrmActivitiesIndexRoute
  CrmCalenderIndexRoute: typeof CrmCalenderIndexRoute
  CrmContactsIndexRoute: typeof CrmContactsIndexRoute
  CrmDashboardIndexRoute: typeof CrmDashboardIndexRoute
  CrmIndustryTypesIndexRoute: typeof CrmIndustryTypesIndexRoute
  CrmLeadSourcesIndexRoute: typeof CrmLeadSourcesIndexRoute
  CrmLeadsIndexRoute: typeof CrmLeadsIndexRoute
  CrmOpportunitiesIndexRoute: typeof CrmOpportunitiesIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmIndexRoute: CrmIndexRoute,
  CrmOpportunitiesAddRoute: CrmOpportunitiesAddRoute,
  CrmOpportunitiesViewRoute: CrmOpportunitiesViewRoute,
  CrmOpportunitiesViewdRoute: CrmOpportunitiesViewdRoute,
  CrmActivitiesIndexRoute: CrmActivitiesIndexRoute,
  CrmCalenderIndexRoute: CrmCalenderIndexRoute,
  CrmContactsIndexRoute: CrmContactsIndexRoute,
  CrmDashboardIndexRoute: CrmDashboardIndexRoute,
  CrmIndustryTypesIndexRoute: CrmIndustryTypesIndexRoute,
  CrmLeadSourcesIndexRoute: CrmLeadSourcesIndexRoute,
  CrmLeadsIndexRoute: CrmLeadsIndexRoute,
  CrmOpportunitiesIndexRoute: CrmOpportunitiesIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface UserRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserDashboardIndexRoute: typeof UserDashboardIndexRoute
  UserInvoicesIndexRoute: typeof UserInvoicesIndexRoute
  UserSettingIndexRoute: typeof UserSettingIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserDashboardIndexRoute: UserDashboardIndexRoute,
  UserInvoicesIndexRoute: UserInvoicesIndexRoute,
  UserSettingIndexRoute: UserSettingIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ChecklistRoute: ChecklistRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AuthenticationForgotRoute: AuthenticationForgotRoute,
  AuthenticationSigninRoute: AuthenticationSigninRoute,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
